# Generated by Django 2.0.1 on 2018-02-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('u_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '普普通通用户')], default=1)),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app02.UserGroup')),
            ],
        ),
    ]
